import "./globals.css"
import type { Metadata } from "next"
import { cn, generalSans, inter } from "@utils/utils"

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export const revalidate = 0

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en">
         <body
            className={cn(inter.variable, generalSans.variable, "bg-[#0c0b0b]")}
         >
            {children}
         </body>
      </html>
   )
}
